### ISSUE TITLE
Cart session empty

### ISSUE THREAD

**Issue by tavicu** [darryldecode/laravelshoppingcart#1]
Hi,

I'm having a problem.

In one route i add an item tot the cart with "Cart::add(455, 'Sample Item', 100.99, 2, array());" and in another route i get the items with "Cart::getContent()".

The problem is that Cart::getContent() always return empty.

I checked the session with Session::get() (and the session id) and the items appear but Cart::getContent always return an empty array.

Can you help me please?

Thanks.

**Comment by darryldecode** [comment]
Hi, it looks like there is a problem with your system when persisting sessions. Have you tried to use the normal Session::put() and then do a Session::get() on another route and check if its working?

**Comment by tavicu** [comment]
HI,

Yes, i trid and it's working. The problem is from Cart construct. When i run Cart::getContent() is rewriting session with a blank array. If i add items to cart and then remove that code from constructor and run getContent everything works ok.

        $this->session->put(
            $this->sessionKey,
            array()
        );

**Comment by darryldecode** [comment]
yes you are right @tavicu. Thank you for your time. I have tagged a new version of it now.

**Comment by Shahnee** [comment]
@tavicu. i am facing the same issue can you help me

**Comment by kaisirahmed** [comment]
sir I am also facing the same issue. Is anyone can help me?

**Comment by kaisirahmed** [comment]
> HI,
> 
> Yes, i tried and it's working. The problem is from Cart construct. When i run Cart::getContent() is rewriting session with a blank array. If i add items to cart and then remove the code that overwrites the session from constructor and run getContent everything works ok.
> 
> This is the code:
> 
> ```
>     $this->session->put(
>         $this->sessionKey,
>         array()
>     );
> ```

can you please tell me where should I change?

**Comment by kaisirahmed** [comment]
@tavicu sir can you please help me. I am new to use this.
