### ISSUE TITLE
Database storage (question)

### ISSUE THREAD

**Issue by o15a3d4l11s2** [darryldecode/laravelshoppingcart#106]
I have checked the documentation for using a different storage, but I still cannot understand exactly how to create a new database storage and what exactly to put in my storage class, so that it can work with the database. And what database models do I need to make it work?

**Comment by darryldecode** [comment]
Hi, sorry for the lacking documentation. Take a look on the tests folder where a Session Mock is injected to the Cart as its storage. This file specifically https://github.com/darryldecode/laravelshoppingcart/blob/master/tests/helpers/SessionMock.php

**Comment by o15a3d4l11s2** [comment]
I have already seen this example:

```
class WishListDBStorage {

    public function has($key)
    {
        // your logic here to check if storage has the given key
    }
    
    public function get($key)
    {
        // your logic here to get an item using its key
    }
    
    public function put($key, $value)
    {
        // your logic here to put an item with key value pair
    }
}
```

What I am missing is how to identify a shopping cart by the `$key`, as the `$key` identifies an item in the cart itself?

**Comment by darryldecode** [comment]
Sorry I think I don't really get what exactly the scenario you are facing. Can you elaborate more? If you mean on how to retrieve an item of a specific shopping card if we have multiple carts like maybe a wishlist cart, you can check the repo of the demo which has multiple carts (shopping cart and wishlist) located here: https://github.com/darryldecode/laravelshoppingcart-demo

It shows how to retrieve items from a wishlist cart and a shopping cart.

**Comment by o15a3d4l11s2** [comment]
My users would have only 1 active cart at any moment.

I understand that I have to create a CartDBStorage, but how should I get the database instance of the cart and load it up so it can be modified and saved back with CartDBStorage?

Would it be better if I submit my whole use-case in StackOverflow, so I don't flood you in GitHub?

**Comment by darryldecode** [comment]
When you inject your DB storage on the Cart Instance on the service provider, doing normal Cart functions like ``Cart::get()``, ``Cart::update`` etc will now use the database storage you configured and manipulate data there.

or am I missing something or not understanding your situation?

**Comment by o15a3d4l11s2** [comment]
I believe I got it. Thanks a lot for the support and time.
I will keep it open for a little longer until I am able to implement it and close it latest tomorrow.

**Comment by darryldecode** [comment]
No problem :) Hope you'll have it sort it out.

**Comment by o15a3d4l11s2** [comment]
I have a follow-up question regarding storing the cart in the database. I have created the `DatabaseStorage` class for storing the items in the database, but how can I identify the instance of the cart that I should return for the user?

When the cart is instantiated it is given a session_key, which uniquely identifies it, but how can I return the proper cart instance for my user?

I have a simple case where a user has 1 shopping cart and inside the cart I have the ordered products.
Obviously the `DatabaseStorage` class has to take care to store the ordered products, but I am not sure how to connect the cart itself with the database, so next time the user logs in I recreate the shopping cart and show it to them.

**Comment by darryldecode** [comment]
See new release & the updated docs.

See also the demo repo: https://github.com/darryldecode/laravelshoppingcart-demo
