### ISSUE TITLE
consultation before use

### ISSUE THREAD

**Issue by robertnicjoo** [darryldecode/laravelshoppingcart#107]
Hi,
I have some questions and this is not an issue as we are in issues section, would be appreciate it if you can help me.

First of all I want to make it clear that I have all the tables that i need such as `products` `coupons` `discounts` `options` `specifications` etc. and why I pop that up? because what I use as title for those tables named as `title` and as I checked in this package files it uses `name` column to add products in cart so my questions are:

1- Will be there any problem with my tables naming and this package naming? (`title` and `name` differences)
2- As my personal experience with laravel, laravel doesn't let us to use classes such as `message` or `attributes` etc. because it uses them itself. And again as I checked files in this package it using attribute class but in my app I'm using `specification` name in order to get my `products attribute` so will be there any problem with this package naming and my tables naming / this package naming and laravel naming?

Thanks in advance.

**Comment by darryldecode** [comment]
Hi, I am closing this now since we are already discussing this stuff on other thread. Thanks!
