### ISSUE TITLE
Total Number of Items

### ISSUE THREAD

**Issue by matalina** [darryldecode/laravelshoppingcart#11]
This is probably a function you want to add.  Most carts these days display the total number of items in the cart.  I see no function for this.  Not hard for me to write, but thought I'd mention it.

**Comment by giovannefc** [comment]
Use:
Cart::getContent()->count();

Cart is a instance of the CartCollection.. You can use all functions of Collect library of laravel.

**Comment by matalina** [comment]
thanks!  didn't realize it was a collection.

**Comment by lostcause** [comment]
Sorry for re-opening a closed issue, but I have a question about this subject. I need the total number of items, but not the Collections' items, but rather the total 'quantities' for all items in the cart. For example, I have Item1 x 2 and Item 2 x 5. The count should be 7, not 2.

**Comment by darryldecode** [comment]
I guess your issue is the same with this pull request: https://github.com/darryldecode/laravelshoppingcart/pull/13

Didn't merged it but I guess I have to.

for the meantime, you can just do like this as workaround.

```
$count = 0;

$items = Cart::getContent();

foreach ($items as $item) {
    $count += $item->quantity;
 }
```

**Comment by pvdptje** [comment]
I submitted a pull request for the same thing, just saw there already was one, my bad.
