### ISSUE TITLE
Data saving from cart

### ISSUE THREAD

**Issue by robertnicjoo** [darryldecode/laravelshoppingcart#111]
Hi,

I saved my cart info as json to my orders table and I noticed that the parent element of your json string is `29` which it shouldn't!

here is sample of it:

```json
"{\"29\":{\"id\":29,\"name\":\"effewf\",\"price\":24524,\"quantity\":1,\"attributes\":[],\"conditions\":[]}}"
```

this is how it looks like in array: (note: `29 => ItemCollection {#720`)

```
CartCollection {#779 ▼
  #items: array:1 [▼
    29 => ItemCollection {#720 ▼
      #config: array:4 [▶]
      #items: array:6 [▼
        "id" => 29
        "name" => "effewf"
        "price" => 24524.0
        "quantity" => 1
        "attributes" => ItemAttributeCollection {#721 ▶}
        "conditions" => []
      ]
    }
  ]
}
```

any idea how I can ignore that before saving my data?

here is my saving method:

```php
public function checkout(Request $request)
    {
      $cartItems = Cart::getContent();         // returning cart content
      $order = new Order();
      
      $data = $cartItems;       // returning cart content
      $order->order_data = json_encode($data);       // saving cart content as json

      $order->user_id = Auth::user()->id;
      $order->address_id = $request->input('address_id');
      $order->payment_id = $request->input('payment_id');
      $order->orderstatus_id = $request->input('orderstatus_id');

      Auth::user()->orders()->save($order);
      Cart::clear();
      return redirect()->route('ordersindex');
    }
```

**Comment by darryldecode** [comment]
@robertnicjoo  hello, since you are saving your cart items as json  directly as object. Its better if you convert them to array first before saving them to your database as json encoded values.

Something like this should work for you:

```php
$items = [];

\Cart::getContent()->each(function($item) use (&$items)
{
    $items[] = $item;
});

$order = new Order();
$order->order_data = json_encode($items);

// more stuff here

$order->save();
```

**Comment by darryldecode** [comment]
@robertnicjoo See new release, updated docs and see the udpated demo repo here: https://github.com/darryldecode/laravelshoppingcart-demo

**Comment by robertnicjoo** [comment]
@darryldecode refer to your comment https://github.com/darryldecode/laravelshoppingcart/issues/111#issuecomment-357129218 all it did was adding `[]` before and after my json data and that `29` as sample still exist.
Anyhow this seem to be taking care of because I can get my data out of it, thanks for all your kind answers and patience.


@darryldecode `again` :-D I saw new demo however 1 part makes me interesting as it is my next step by this package, and that's adding attributes to my cart so later I can save it in my orders table.

As I saw it here in `CartController`

```
$customAttributes = [
            'color_attr' => [
                'label' => 'red',
                'price' => 10.00,
            ],
            'size_attr' => [
                'label' => 'xxl',
                'price' => 15.00,
            ]
        ];
        \Cart::session($userId)->add($id, $name, $price, $qty, $customAttributes);
```

which is exactly what i need, here you have 2 array `color_attr` and `size_attr` what if I want to get this 3 parts dynamically?

1-  `color_attr` (to be whatever is my option name) `example COLOR`
2-  `label` (to be whatever is my suboption name) `example RED`
3-  `price` (to be whatever is my suboption price value) `example 10.00`

here is my adding function to cart


```
public function addingItem($id)
    {
      $product = Product::where('id', $id)->firstOrFail();
      Cart::add(array(
        'id' => $product->id,
        'name' => $product->title,
        'price' => $product->price,
        'quantity' => 1,
        'attributes' => array()
      ));
      Session::flash('success', 'This product added to your cart successfully.');
      return redirect()->back();
    }
```

Ps: I promise you I would go away after fixing this at least for 1 week and let you breath. LOL.


Thanks.

**Comment by robertnicjoo** [comment]
Maybe I should continue here https://github.com/darryldecode/laravelshoppingcart/issues/109 and I was wrong to asking it here!

anyway wherever you answer is fine by me :-p
