### ISSUE TITLE
Check if item exist in cart?

### ISSUE THREAD

**Issue by bloggervista** [darryldecode/laravelshoppingcart#128]
Sorry but i coulnot find this in readme? Can anyone tell me how to check if the item exist in cart ?

Say i have item with item of id 21 and if user want to add new item i may not want to allow him but for that i need to check if item exist in cart or not ?

is there any method ?

**Comment by frezno** [comment]
@bloggervista  take a look into the Cart class. There's a method:

```
/**
     * check if an item exists by item ID
     *
     * @param $itemId
     * @return bool
     */
    public function has($itemId)
    {
        return $this->getContent()->has($itemId);
    }
```

ie you can use `has` for checking whether the item already exist in the cart, eg:

```
public function addToCart(Request $request)
{
        $input = $request->all();

        if (Cart::has($input['id'])) {
            // do whatever you want

**Comment by bloggervista** [comment]
@frezno  Thank you so much bro :)
