### ISSUE TITLE
Conclusion: don't install laravel/framework v5.5.40

### ISSUE THREAD

**Issue by masterpieceicang** [darryldecode/laravelshoppingcart#130]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.39
    - Conclusion: don't install laravel/framework v5.5.38
    - Conclusion: don't install laravel/framework v5.5.37
    - Conclusion: don't install laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.35
    - Conclusion: don't install laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.33
    - Conclusion: don't install laravel/framework v5.5.32
    - Conclusion: don't install laravel/framework v5.5.31
    - Conclusion: don't install laravel/framework v5.5.30
    - Conclusion: don't install laravel/framework v5.5.29
    - Conclusion: don't install laravel/framework v5.5.28
    - Conclusion: don't install laravel/framework v5.5.27
    - Conclusion: don't install laravel/framework v5.5.26
    - Conclusion: don't install laravel/framework v5.5.25
    - Conclusion: don't install laravel/framework v5.5.24
    - Conclusion: don't install laravel/framework v5.5.23
    - Conclusion: don't install laravel/framework v5.5.22
    - Conclusion: don't install laravel/framework v5.5.21
    - Conclusion: don't install laravel/framework v5.5.20
    - Conclusion: don't install laravel/framework v5.5.19
    - Conclusion: don't install laravel/framework v5.5.18
    - Conclusion: don't install laravel/framework v5.5.17
    - Conclusion: don't install laravel/framework v5.5.16
    - Conclusion: don't install laravel/framework v5.5.15
    - Conclusion: don't install laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.13
    - Conclusion: don't install laravel/framework v5.5.12
    - Conclusion: don't install laravel/framework v5.5.11
    - Conclusion: don't install laravel/framework v5.5.10
    - Conclusion: don't install laravel/framework v5.5.9
    - Conclusion: don't install laravel/framework v5.5.8
    - Conclusion: don't install laravel/framework v5.5.7
    - Conclusion: don't install laravel/framework v5.5.6
    - Conclusion: don't install laravel/framework v5.5.5
    - Conclusion: don't install laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - don't install illuminate/container v5.6.11|don't install laravel/framework v5.5.0
    - don't install laravel/framework v5.5.0|don't install illuminate/container v5.6.11
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.5, v5.5.6,v5.5.7, v5.5.8, v5.5.9].
    - Installation request for illuminate/container (locked at v5.6.11) -> satisfiable by illuminate/container[v5.6.11].

**Comment by frezno** [comment]
I'm working with v5.5.36 without problems

Where do you get those messages from?

**Comment by masterpieceicang** [comment]
I just change my composer.json 
before 
`"laravel/framework": "5.5.x",`
after
`"laravel/framework": "5.5.40",`

**Comment by theshreyansh** [comment]
Any update on this error? I am facing the same. 
Console output

>composer require --dev laravel/dusk:^2.0
PHP Deprecated:  Directive 'track_errors' is deprecated in Unknown on line 0

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
You are running Composer with SSL/TLS protection disabled.
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.44
    - Conclusion: don't install laravel/framework v5.5.44
    - aacotroneo/laravel-saml2 0.0.1 requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4
.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - aacotroneo/laravel-saml2 0.0.2 requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4
.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.5.44
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.5.44
    - Installation request for laravel/framework (locked at v5.5.44, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.44].
    - Installation request for aacotroneo/laravel-saml2 ^0.0 -> satisfiable by aacotroneo/laravel-saml2[0.0.1, 0.0.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by icangku** [comment]
Problem 1
- Conclusion: remove laravel/framework v5.5.44
- Conclusion: don't install laravel/framework v5.5.44

**Comment by Ljiayi** [comment]
vagrant@homestead:/var/www$ composer require laravel/horizon
Using version ^3.1 for laravel/horizon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.34
    - laravel/horizon v3.1.0 requires illuminate/queue ~5.7.0|~5.8.0|~5.9.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - laravel/horizon v3.1.1 requires illuminate/queue ~5.7.0|~5.8.0|~5.9.0 -> satisfiable by illuminate/queue[5.7.17, 5.7.18, 5.7.19, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.2, v5.8.3, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/queue 5.7.17|don't install laravel/framework v5.5.34
    - don't install illuminate/queue 5.7.18|don't install laravel/framework v5.5.34
    - don't install illuminate/queue 5.7.19|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.0|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.1|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.10|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.11|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.15|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.2|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.20|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.21|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.22|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.23|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.26|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.27|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.28|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.3|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.4|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.5|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.6|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.7|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.8|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.7.9|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.0|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.11|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.12|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.2|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.3|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.4|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.8|don't install laravel/framework v5.5.34
    - don't install illuminate/queue v5.8.9|don't install laravel/framework v5.5.34
    - Installation request for laravel/framework (locked at v5.5.34, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.34].
    - Installation request for laravel/horizon ^3.1 -> satisfiable by laravel/horizon[v3.1.0, v3.1.1].


Installation failed, reverting ./composer.json to its original content.

how to resolve?

**Comment by elephantux** [comment]
@Ljiayi did you solve problem?
