### ISSUE TITLE
Tax condition to be always last

### ISSUE THREAD

**Issue by criting** [darryldecode/laravelshoppingcart#135]
Hello. I really like this package, however, I have a little problem and I can't seem to fix it. In my country, on every sale, we have 20% tax on the total sum, after everything, after all the discounts, sales and etc applied.

The problem with my case is that when I try to set a discount, the 20% tax is already applied, so it does this discount on the sum that already has this 20% tax applied. It should be the other way around. The tax should always be last. I apply them in different functions, maybe this causes the problem, but here is my code.

```
public function sell(Request $request){
....

$tax = new \Darryldecode\Cart\CartCondition(array(
                'name' => 'ДДС',
                'type' => 'tax',
                'target' => 'subtotal',
                'value' => '+20%',
                'attributes' => array(
                    'description' => 'Value added tax',
                    'more_data' => 'more data here'
                )
            ));
....
}
```

And this is my function that I apply the discount with:
```
public function setDiscount(Request $request, $barcode){
....
$condition = new \Darryldecode\Cart\CartCondition(array(
                'name' => 'Отстъпка',
                'type' => 'discount',
                'target' => 'subtotal',
                'value' => '-'.$setDiscount.'%',
                'attributes' => array(
                    'description' => 'Value added tax',
                    'more_data' => 'more data here'
                )
            ));
}
```
....

**Comment by darryldecode** [comment]
hello @criting , have you check on the "order" parameter when adding a condition? https://github.com/darryldecode/laravelshoppingcart#conditions

**Comment by criting** [comment]
yes @darryldecode , I set order to 1 in the Tax condition and order 2 to the discount one, and still the same effect

**Comment by darryldecode** [comment]
hello @criting the bigger the order value the last thing it will be applied. So if you want the tax condition to be applied on last, put bigger value than any of the conditions applied.

**Comment by criting** [comment]
I now changed it, but I can't see if it calculates right, because the Tax should apply on subtotal, and it's always applying it on total for some reason, here is the code:

```
$condition = new \Darryldecode\Cart\CartCondition(array(
                'name' => 'Отстъпка',
                'type' => 'discount',
                'target' => 'subtotal',
                'value' => '-'.$setDiscount.'%',
                'attributes' => array(
                    'description' => 'Value added tax',
                    'more_data' => 'more data here'
                ),
                'order' => 1
            ));

            Cart::condition($condition);
            Cart::session($userId)->condition($condition);
```

and it always puts in on the total, not the subtotal as it's stated :/

**Comment by darryldecode** [comment]
sorry if it doesn't fit your requirements @criting. subTotal() are meant to get cart absolute end sum without the applied conditions such as before taxes, fees, etc are calculated/applied. Then we have the getTotal() with all conditions applied/calculated. It is stated in the documentation. If you really need to put tax to be calculated on sub total, then consider TAX as not part of the conditions. You can do it manually to fit your needs like get the subtotal and apply a tax and display it. 

In some cases, VAT are added on per item bases because some items have different VAT value. It really falls on your requirement because some are unique on its own.

**Comment by criting** [comment]
Yeah, got it. I thought it worked the same. Because here we put discounts on subtotal and TAX on total after all the discounts are calculated.

**Comment by darryldecode** [comment]
@criting don't be confused with "target" parameter. There is only two target values "subtotal" and "item".  When you add a condition to a cart bases, you put target "subtotal", means this conditions are applied on the subtotal value and will have resulting getTotal(). When you add a condition on anper item bases, you will put target "item".

As stated on the documentation:
"When adding a condition on a cart bases, the 'target' should have value of 'subtotal'. And when adding a condition on an item, the 'target' should be 'item'. The order of operation also during calculation will vary on the order you have added the conditions."

Hope that helps you.

**Comment by criting** [comment]
Yeah, I think it worked out. Thank you very much!

**Comment by darryldecode** [comment]
@criting might change this on next release so conditions can be applied to either subtotal or total manually to avoid confusions.

**Comment by darryldecode** [comment]
@criting you may want to take a look on new release https://github.com/darryldecode/laravelshoppingcart/releases/tag/4.0.0 maybe that solves your confusions
