### ISSUE TITLE
same quantity added two time, given not correct total quantity 

### ISSUE THREAD

**Issue by moretolike** [darryldecode/laravelshoppingcart#139]
I added 10 quantity and after then again added 10 quantity. it gives total 30.

**Comment by frezno** [comment]
in this case there's something wrong with your code.
How do you handle adding product/qty?

**Comment by moretolike** [comment]
**$input['id'] = $requestData['product_id'];
                            $input['name'] = $product_detail->product_name;
                            $input['price'] = $product_detail->current_price;
                            $input['mrp'] = $product_detail->mrp;
                            $input['quantity'] = $requestData['quantity'];
                            $input['attributes'] = ['img'=>$product_detail->product_img];
                Cart::add($input); 
                $cartCollection = Cart::getContent();
                print_r($cartCollection);**


every time **$requestData['quantity']** value is 1.
But first time its prints 1 and second time it's print 3 quantity.

**Comment by moretolike** [comment]
Thanks for suggestion. I found,what the issue.

**Comment by malaymehta** [comment]
@darryldecode  This issue needs to be closed. @moretolike - You can close this issue as well.
