### ISSUE TITLE
Cart::removeItemCondition

### ISSUE THREAD

**Issue by scottpd** [darryldecode/laravelshoppingcart#14]
It seems Cart::removeItemCondition($itemId, $conditionName) has no effect.

**Comment by darryldecode** [comment]
Hi @scottpd, could you please give your scenario on this? Thanks!

**Comment by scottpd** [comment]
$saleCondition = new \Darryldecode\Cart\CartCondition(array(
            'name' => 'SALE 5%',
            'type' => 'tax',
            'target' => 'item',
            'value' => '-5%',
        ));

$product = array(
            'id' => 456,
            'name' => 'Sample Item 1',
            'price' => 100,
            'quantity' => 1,
            'attributes' => array(),
            'conditions' => $saleCondition
        );

Cart::add($product);
print_r(Cart::getContent(),true);
Cart::removeItemCondition(456,'SALE 5%');
print_r(Cart::getContent(),true);

The contents printed before and after the removeItemCondition call are exactly the same - nothing is removed.

**Comment by darryldecode** [comment]
Hi @scottpd,

Please add the conditions as in array format like so:

```
$product = array(
'id' => 456,
'name' => 'Sample Item 1',
'price' => 100,
'quantity' => 1,
'attributes' => array(),
'conditions' => [$saleCondition]
);
```

There was a problem in that API when added not in array, I will fix that shortly and will release a new version sooner. For the meantime you can do it like that as a workaround.

Also, I checked that packagist was not pulling the latest release which is the 2.2.0 version which contains this new Cart API (which is weird).

Please do: ```composer update "darryldecode/cart"```

Thank you for your time :)

**Comment by scottpd** [comment]
No problem - thanks for the update.

**Comment by darryldecode** [comment]
024ede89450ad824b76da6d743b5a59413d1a85f
