### ISSUE TITLE
Cart::getContent() Ordering

### ISSUE THREAD

**Issue by ravigaudani** [darryldecode/laravelshoppingcart#143]
The Order of cart item is changed while I'm updating any Item in cart
![before](https://user-images.githubusercontent.com/23468739/45621616-9576f380-ba9e-11e8-87e4-87aa443fe779.PNG)

Once I update quantity for black chair and view cart It goes down
![after](https://user-images.githubusercontent.com/23468739/45621641-ad4e7780-ba9e-11e8-8db4-d2cde47f48fc.PNG)

**Comment by darryldecode** [comment]
Hello @ravigaudani , the return data is a collection, you can use available methods from laravel's collection like sorting and custom sorts https://laravel.com/docs/5.6/collections#available-methods
