### ISSUE TITLE
Type Hinting the Cart

### ISSUE THREAD

**Issue by kadeprice** [darryldecode/laravelshoppingcart#15]
I've tried to type hint the Cart so that I'm not doing static calls. From what I understand better for unit testing. 

But the problem is that the _construct requires session, events and so on. Is there any way to do this?

I want to be able to do something like $this->cart-clear() or $this->cart->add()

**Comment by darryldecode** [comment]
Hello,

if you look at the Docs,

```'Cart' => 'Darryldecode\Cart\Facades\CartFacade'```

that points to a "cart" key on the laravel's services registry.

which we have registered using:

``` 'Darryldecode\Cart\CartServiceProvider' ```

You can read more about it here: http://laravel.com/docs/5.0/facades

For type hinting, you can use third party package to enable type hinting with laravel's facade system.

Take a look on this: https://github.com/barryvdh/laravel-ide-helper

**Comment by kadeprice** [comment]
That pointed me in the right direction so app()->cart->add() works. I then created a property and assigned it in my construct so now $this->cart->add() is doing it. Thanks for pointing me in the right direction. I had tried to setup a bind before, but I didn't realize you already did.

**Comment by darryldecode** [comment]
no problem :+1:
