### ISSUE TITLE
Non-static method Darryldecode\Cart\Cart::add() should not be called statically

### ISSUE THREAD

**Issue by lohitbadiger** [darryldecode/laravelshoppingcart#157]
<?php

namespace App\Http\Controllers;

// use Darryldecode\Cart\CartCondition;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Product;
use Darryldecode\Cart\Cart;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
        $cartItems=Cart::content();
        return view('cart.index', compact('cartItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()

    
    {
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::find($id);
    Cart::add($id,$product->name,1,$product->price,['size'=>'medium']);
        // Cart::add(455, 'Sample Item', 100.99, 2, array());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

**Comment by darryldecode** [comment]
Hi don't forget to put a forward slash ```\Cart::add()```

**Comment by lohitbadiger** [comment]
where?

**Comment by christophemassin** [comment]
Before the cart \Cart::add 

Don't add use Cart neither, if well configured, you don't need it. 

```
namespace App\Services\User;

use App\Services\AbstractService;
use App\ValueObjects\Cart\ItemObject;

class CartService extends AbstractService
{
	public function addItem(ItemObject $itemObject)
	{
		\Cart::add($itemObject->getItems());

	}
```

**Comment by indersein-wiznox** [comment]
> Hi don't forget to put a forward slash `\Cart::add()`

Thanks this problem is solved

**Comment by tasmanian-devil** [comment]
"> Before the cart \Cart::add
> 
> Don't add use Cart neither, if well configured, you don't need it."
How do i need to configure that "\" would work, because it doesn't now...

**Comment by droidrobin** [comment]
<?php
namespace App\Http\Controllers;
use App\Product;
use Darryldecode\Cart\Cart;

class CartController extends Controller
{
    public function add(Product $product)
    {

        $userId = auth()->user()->id;
        Cart::session($userId)->add(array(
            'id' => $product->id,
            'name' => $product->name,
            'price' => $product->price,
            'quantity' => 4,
            'attributes' => array(),
            'associatedModel' => $product
        ));
        return back();

    }

    public function index()
    {
        return view('cart.index');
    }
}

Followed Github:-https://github.com/darryldecode/laravelshoppingcart
As per your Configuration:
Getting Error as:-
Non-static method Darryldecode\Cart\Cart::session() should not be called statically

**Comment by droidrobin** [comment]
> Non-static method Darryldecode\Cart\Cart::session() should not be called statically

**Comment by xaverymsomi** [comment]
write this in your controller
use Cart;
