### ISSUE TITLE
Not specified cart duplicates on for all clients

### ISSUE THREAD

**Issue by SorokaKostiantyn** [darryldecode/laravelshoppingcart#158]
Hi!
I think that is not new problem.
In my project for not authorised client cart entity is same....
Storage - DB
All cart data for not authorized client saved in DB with identifier 4yTlTDKu3oJOfzD_cart_items.

What is the best way to solve this problem?

**Comment by darryldecode** [comment]
hello, did you use ```\Cart::session($key)``` before calling any cart function? the $key is a unique identifier of a cart that will be bind to it. It can be a user ID if you want to bind the cart to a user.

**Comment by SorokaKostiantyn** [comment]
I use it only for authorized clients, but for not authorized users I process cart operation without key ( \Cart::add() ).
Now I solved my problem by creating uniqId in user cookie and use it like key.
