### ISSUE TITLE
Add conditions to existing products in cart

### ISSUE THREAD

**Issue by lostcause** [darryldecode/laravelshoppingcart#16]
Hi all,

I have a question about adding per-item conditions to already existing products in cart. I have a 'cart' page, which contains a form for coupons, which can be assigned to certain products/categories in the shop, so when the user is filling in his coupon, he might already have the product(s) on sale in the cart. Is there a way to assign a per-item condition to a certain existing product in cart.

Thank you.

**Comment by darryldecode** [comment]
Hello,

For now, it's not possible to directly insert the new item condition on the already existing item on the cart. But you can do the same thing by getting the that item, and push to its conditions array. Just make sure that the conditions you have added on that item is in array format. Please see below:

```
$itemCondition = new \Darryldecode\Cart\CartCondition(array(
    'name' => 'Coupon 101',
    'type' => 'sale',
    'target' => 'item',
    'value' => '-5%',
));

$productID = 456;

$product = Cart::get($productID);

if( is_array($product['conditions']) )
{
    array_push($product['conditions'], $itemCondition);
}
else
{
    $product['conditions'] = $itemCondition;
}

Cart::update($productID, array(
  'conditions' => $product['conditions'] // the newly updated conditions
));
```

I haven't tested the code above but you get the idea as a workaround for the meantime.
I'll definitely add this when I'll have the time.
Let me know if that works for you.

**Comment by lostcause** [comment]
Worked like a cham! Thanks for the hints, and I guess it would be a great addition to the package if you could add this to it.

Thanks again!

**Comment by darryldecode** [comment]
Hello @lostcause , this is now added: see 339bae910a8c285c2591454370b1f16819f55427

Please update with the new tagged version.

Thanks :)
