### ISSUE TITLE
->totalquantity() in addition of count()

### ISSUE THREAD

**Issue by Sennik** [darryldecode/laravelshoppingcart#17]
Of course not so difficult to calculate myself but it would be nice to have a function to get the total quantity of all items in the cart. Now I have a quantity of 14 and stil just 1 when I use count().

**Comment by darryldecode** [comment]
Hello @Sennik , this is now added: see 339bae910a8c285c2591454370b1f16819f55427

Please update with the new tagged version.

Thanks :)

**Comment by Sennik** [comment]
Thanks! Using it allready!
