### ISSUE TITLE
event error

### ISSUE THREAD

**Issue by alighasemzadeh** [darryldecode/laravelshoppingcart#170]
````
Call to undefined method Illuminate\Events\Dispatcher::fire() (View: /home2/shirazsoft/resources/views/layouts/app.blade.php) (View: /home2/shirazsoft/resources/views/layouts/app.blade.php)
````
When I call `\Cart::getContent()`
my laravel version is 5.8

**Comment by Mo7sin** [comment]
The fire method (which was deprecated in Laravel 5.4) of the `Illuminate/Events/Dispatcher` class [has been removed](https://github.com/laravel/framework/pull/26392). You should use the `dispatch` method instead.

**Comment by alighasemzadeh** [comment]
@Mo7sin @darryldecode 
https://github.com/darryldecode/laravelshoppingcart/blob/2f84a003d17c658287bc0201be4c9a07f09612fc/src/Darryldecode/Cart/Cart.php#L834

Source should change becasue it has it.

**Comment by Mo7sin** [comment]
@alighasemzadeh Yeah, that should get updated ofcourse!

**Comment by alighasemzadeh** [comment]
@Mo7sin 
Please make pull request.

**Comment by darryldecode** [comment]
Hi all! Anyone working on a PR?

**Comment by darryldecode** [comment]
Hi all! nevermind for a PR. I have already pushed a quick fix. Thanks!
