### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by kadeprice** [darryldecode/laravelshoppingcart#18]
Will you be updating the cart for Laravel 5.1? I can't update to 5.1 until the cart will accept it. 

Problem 1
    - Installation request for darryldecode/cart dev-master -> satisfiable by darryldecode/cart[dev-master].
    - Conclusion: remove laravel/framework v5.1.1
    - Conclusion: don't install laravel/framework v5.1.1
    - darryldecode/cart dev-master requires illuminate/validation 5.0.*@dev -> satisfiable by illuminate/validation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.4].
    - don't install illuminate/validation v5.0.0|don't install laravel/framework v5.1.0
    - don't install illuminate/validation v5.0.22|don't install laravel/framework v5.1.0
    - don't install illuminate/validation v5.0.25|don't install laravel/framework v5.1.0
    - don't install illuminate/validation v5.0.26|don't install laravel/framework v5.1.0
    - don't install illuminate/validation v5.0.28|don't install laravel/framework v5.1.0
    - don't install illuminate/validation v5.0.4|don't install laravel/framework v5.1.0
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1].

**Comment by argb** [comment]
I have the same problem.

**Comment by darryldecode** [comment]
I will be updating the Cart shortly.. I'll post here once it's done. Thanks for the heads up!

**Comment by argb** [comment]
when required,should remove the specific version number

**Comment by darryldecode** [comment]
Hello, you can do now ```composer update "darryldecode/cart"```
see 51139557187a2d0fdf87d230ea444f735b636762
