### ISSUE TITLE
 A non well formed numeric value encountered

### ISSUE THREAD

**Issue by audetcameron** [darryldecode/laravelshoppingcart#180]
error:  A non well formed numeric value encountered exception when calling getTotal() and cart value is over 1000 with a condition  applied.   
example exception: Darryldecode\\Cart\\CartCondition->apply('1,154.00', '-10.00')

I was able to fix it by adding-
$totalOrSubTotalOrPrice = str_replace(',', '', $totalOrSubTotalOrPrice);
on line 191 CartCondition.php

**Comment by pdois** [comment]
#187

**Comment by afbora** [comment]
@audetcameron You can get total value without formatted like that: `Cart::getTotal(false)`

**Comment by audetcameron** [comment]
> @audetcameron You can get total value without formatted like that: `Cart::getTotal(false)`

thanks @afbora , I see I should be doing that from the start.
