### ISSUE TITLE
Possibility to have attributes on conditions.

### ISSUE THREAD

**Issue by gjportegies** [darryldecode/laravelshoppingcart#19]
What are you guys thinking of adding the possibility to have attributes on conditions. I have a condition with the name 'discount'. This because I only want to have the option to have one 'discount' rule so I can the value if they enter another promo code. But I would like to add some more information on this condition due attributes.

**Comment by darryldecode** [comment]
makes sense..we'll add that shortly :+1:

**Comment by darryldecode** [comment]
Hi @gjportegies , this is now added. You can do ```composer update "darryldecode/cart"``` to get the latest updates. See: 7d25d94766ba4648edea32269f3c4688d8c9b2c8

Thank you for your time.

**Comment by gjportegies** [comment]
Thanks you!
