### ISSUE TITLE
Change the db session of unauthenticated user to authenticated user after login

### ISSUE THREAD

**Issue by debuGhy** [darryldecode/laravelshoppingcart#191]
I have added the model to the package and also maintaining different sessions for different users. I am using the database session. Now if a user is not logged in and adds something to the cart, it is saved in database with the session id. But I am trying to find a way to change the session id to the user id after the user logs in. How can that be done? Kindly help me.

**Comment by debuGhy** [comment]
Achieved it creating a listener for login event.

**Comment by PatrissolJuns** [comment]
> Achieved it creating a listener for login event.

More explanation please
