### ISSUE TITLE
Not able to install it in laravel 6

### ISSUE THREAD

**Issue by debuGhy** [darryldecode/laravelshoppingcart#192]
I am getting this error when I try to install it in Laravel 6. Kindly help me out in this.

$ composer require "darryldecode/cart"
Using version ^4.0 for darryldecode/cart
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install darryldecode/cart 4.0.4
    - Conclusion: don't install darryldecode/cart 4.0.3
    - Conclusion: don't install darryldecode/cart 4.0.2
    - Conclusion: don't install darryldecode/cart 4.0.1
    - Conclusion: remove laravel/framework v6.0.1
    - Installation request for darryldecode/cart ^4.0 -> satisfiable by darryldecode/cart[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4].
    - Conclusion: don't install laravel/framework v6.0.1
    - darryldecode/cart 4.0.0 requires illuminate/translation 5.0.*|5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> satisfiable by illuminate/translation[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/translation 5.0.x-dev|don't install laravel/framework v6.0.1

**Comment by mtawil** [comment]
@darryldecode Please we are wait your upgrade!

**Comment by darryldecode** [comment]
Hi. Sorry will update it next week. Im on vacation at the moment and on mobile. Will be back by sunday and will update things.

**Comment by Blum** [comment]
> @darryldecode Please we are wait your upgrade!

Just fork and fix it temporary until the update comes. Use #190

**Comment by debuGhy** [comment]
ok. I will wait for the update then

**Comment by darryldecode** [comment]
https://github.com/darryldecode/laravelshoppingcart/releases/tag/4.0.5

**Comment by debuGhy** [comment]
Do we need to download the zip manually and use it in laravel project or we can composer require against the version?

**Comment by darryldecode** [comment]
Hi @debuGhy , you just install it like the usual. No need to manually install it. If you are updating, you can also specify specific version which is 4.0.5 to force update.
