### ISSUE TITLE
only add 2 product

### ISSUE THREAD

**Issue by caturseptian** [darryldecode/laravelshoppingcart#216]
"laravel/framework": "^6.2",
"darryldecode/cart": "^4.0",

before redirect to cart page
![image](https://user-images.githubusercontent.com/13551379/71713752-a0919680-2e3d-11ea-9911-b76a6d4bc237.png)

and this is after redirect to cart page, only 2 product
![image](https://user-images.githubusercontent.com/13551379/71713797-ca4abd80-2e3d-11ea-92cb-490a072d8fd1.png)

**Comment by AndrijKlyon** [comment]
in .ENV file try to change settings:
from 
SESSION_DRIVER=cookie
to
SESSION_DRIVER=file

**Comment by caturseptian** [comment]
thanks a lot
