### ISSUE TITLE
Documentation for associatedModel appears incorrect

### ISSUE THREAD

**Issue by dougfelton** [darryldecode/laravelshoppingcart#230]
The docs suggests this to add an item to the cart:

```php
Cart::session($userID)->add(array(
    'id' => $rowId,
    'name' => $Product->name,
    'price' => $Product->price,
    'quantity' => 4,
    'attributes' => array(),
    'associatedModel' => $Product
));
```

Then in several places in the docs it suggests referencing the associated model like this:

```php
$row->model->name
```

I was unable to access the associated model that way, though the following DID work for me:

```php
$row->associatedModel->name
```

It looks like the docs may be showing an incorrect way to access the associated model.

Thanks for all of your work on this package.  It's really nice.

**Comment by darryldecode** [comment]
Thank you. Updated already the documentation 👍
