### ISSUE TITLE
Rounding Issue caused when using getPriceSumWithConditions()

### ISSUE THREAD

**Issue by ShamarKellman** [darryldecode/laravelshoppingcart#235]
Input: 
  Price: 40.25
  Quantity: 2
  Condition per Item Basis: tax, 17.5% 

Output: 
  Price With Conditions: 47.29
  Price Sum With Conditions: 94.59  -- (Should Be 94.58)

Issue is cause by not formatting the parsedRawValue before doing calculations in the CartConditions Class

**Comment by frezno** [comment]
no, @ShamarKellman , actually it's working correctly.
The result of 2 x 40.25 + tax is 94,5875 and that's rounded up to 94.59

**Comment by ShamarKellman** [comment]
I changed the method of doing calculations to achieve the correct values. You should consider looking at http://blog.verraes.net/2011/04/fowler-money-pattern-in-php/ to do more accurate calculations.

**Comment by frezno** [comment]
whatever makes you happy, @ShamarKellman , it's your money
