### ISSUE TITLE
Unique item identifier

### ISSUE THREAD

**Issue by iapparatus** [darryldecode/laravelshoppingcart#24]
Have you considered to use something other then Item ID for Cart::update() and Cart::remove() functions? In cases where cart holds multiple instances of the same Item ID how do you work with items in the cart?

**Comment by darryldecode** [comment]
Hello @iapparatus 

I am a bit confused with your question, can please more elaborate your scenario. Thanks!

**Comment by iapparatus** [comment]
@darryldecode Maybe I'm missing something but here is my scenario. I'm adding item '456' to the cart twice. Instead of increasing the quantity of item in the cart I want to add items as rows and set some options so both items are unique products.

There are some other carts that document having $rowId set to something unique and using that to perform updates on the item.

    $rowId = 'da39a3ee5e6b4b0d3255bfef95601890afd80709';
    Cart::remove($rowId);

**Comment by darryldecode** [comment]
Hello @iapparatus,

I don't know what you are trying to do, ID is the item's identifier on the cart, thus with that we can do ```Cart::remove(456);``` and ```Cart::get($itemId);```

You can even do:
```
$rowId = 'da39a3ee5e6b4b0d3255bfef95601890afd80709';
Cart::add(array(
    'id' => $rowId,
    'name' => 'Sample Item',
    'price' => 67.99,
    'quantity' => 4,
    'attributes' => array(
        'product_id' => 456
    )
));
```
But in that case, this is what to do to retrieve it,
```
Cart::get('da39a3ee5e6b4b0d3255bfef95601890afd80709');
```

Honestly, I don't understand why you would add the same Item as different item on the cart rather than increment its quantity.

**Comment by iapparatus** [comment]
@darryldecode Thank you for clarifying. In my case the items in the cart are not physical products but classes with different attributes that will affect per item price, even though they are the same product, so simply increasing the quantity is not an option. I need each item in the cart to be unique.

**Comment by manoj10029** [comment]
Hello @darryldecode,

Case as follow:
I have two registration of user. Two different user should login with same browser and try to add items in cart. Now when I am trying to retrieve any one of users item, I have got all items added by both users. I want only retrieve items as per user who added themselves and not both user. 

In short I need multi cart instance which is helpful for this case. But, yet problem is that, how I can set different identity for each cart. or Muliti - cart - instance.

**Comment by matejsvajger** [comment]
@darryldecode I think what @iapparatus meant here is that the `$rowId`s would be automatically generated by Cart based on the item id and its' attributes; It's a very common practice to have the same Product ID from database associated with different attributes, which can represent the same type of product on the invoice, but it's a different product in the warehouse or in shipping.

For example: You have a T-Shirt Business and you sell a Red T-Shirt from Brand-X. This T-Shirt has different Sizes: [S, M, L, XL] which are attributes of a product. On the website a customer wants to buy 2 Red T-Shirts the size of S and 1 Red T-Shirt the size of XL.

If you just add them under the Product ID, attributes for one will get overwritten, where you want this to be displayed as a separate item in the Cart::contents()

**Comment by darryldecode** [comment]
@matejsvajger @manoj10029 Hi guys, please refer to this discussion, this might help: https://github.com/darryldecode/laravelshoppingcart/issues/69
