### ISSUE TITLE
Update cart issue

### ISSUE THREAD

**Issue by RicardoRL** [darryldecode/laravelshoppingcart#241]
I'm trying to update the cart using an array as second argument:

`Cart::update($id, array(
            'quantity' => array(
                'relative' => false,
                'value' => $request->quantity
            ),
            'associatedModel' => $cerveza
        ));`

but the method is not working, I have the following results

Darryldecode\Cart\CartCollection {#368 ▼
  #items: array:3 [▼
    152 => Darryldecode\Cart\ItemCollection {#349 ▶}
    37 => Darryldecode\Cart\ItemCollection {#352 ▶}
    "${id}" => array:2 [▶]
  ]
}

The  "${id}" it supposed to be the id with attributes for updating but the function is adding it

I read that the method has a mistake or something like that but I don't know what it is, does anybody could help me?

**Comment by frezno** [comment]
@RicardoRL associating a model only works when adding an item to the cart and not when updating!

**Comment by RicardoRL** [comment]
Thanks for answering, I remove the associated model, I was doing some tests whit the updating, but I had the same result, the method is not updating the quantity but adding a new item
