### ISSUE TITLE
[Laravel 6] Call to undefined method Darryldecode\Cart\Cart::getContents()

### ISSUE THREAD

**Issue by gieart87** [darryldecode/laravelshoppingcart#242]
I've just followed the installation steps.

The config:
`'providers' => [
     //..............
     Darryldecode\Cart\CartServiceProvider::class,
],

'aliases' => [
     //...........
     'Cart' => Darryldecode\Cart\Facades\CartFacade::class,
]`

And tried to use in the cartController like this:

<img width="661" alt="Screen Shot 2020-04-27 at 05 39 17" src="https://user-images.githubusercontent.com/145084/80321720-8a26a500-8849-11ea-9191-d8679cbfbb68.png">

Can anyone here help me to solve this issue?

**Comment by RicardoRL** [comment]
The method is getContent() no getContents()

**Comment by gieart87** [comment]
> The method is getContent() no getContents()

My bad. thanks @RicardoRL !
