### ISSUE TITLE
How to guests continue with same cart when they login 

### ISSUE THREAD

**Issue by natjesada** [darryldecode/laravelshoppingcart#250]
Can someone show or explains for me how to do that.
Thank you.

**Comment by petrovgit** [comment]
Before the user login, you need to get the items from the cart, like assign them to an array. Once the login is successful, get the items and store them in the new cart which will have a session with the logged user_id. Don't forget to clear the guest cart.

**Comment by gaiahub** [comment]
did anyone successfully get this to work?

**Comment by liamjcooper** [comment]
I managed to get this working by utilising Laravel's auth events.

In the EventServiceProvider's listen array, I listened for these 2 events:
```php
\Illuminate\Auth\Events\Attempting::class => [
    \App\Listeners\PrepareCartTransfer::class
],
\Illuminate\Auth\Events\Login::class => [
    \App\Listeners\TransferGuestCartToUser::class
]
```

In the attemping event, I have a listener that flashes the guest session ID and their cart into their session ready for the next page, like so:
```php
if (\Auth::guest()) {
    session()->flash('guest_cart', [
        'session' => session()->getId(),
        'data' => cart()->getContent() // i have a global cart() function in my app which sets the correct session
    ]);
}
```

Then in the login event, I use the flashed data to merge the items into the user cart. You could just replace the user's cart rather than merge it in to make your life easier but I decided to merge it in.
```php
$userCart = cart()->session($event->user->id);

$guestCartItems = session('guest_cart.data')->toArray();

// my app does not require quantities so I can just add new items as lines regardless of duplicates.
// if your app needs to merge in duplicate product quantities, I would probably create one array
// of unique products to add and one that will update existing ID's in your cart. Or just wipe the
// user's cart and replace it entirely.
if ($userCart->getContent()->isNotEmpty()) {
    // user cart has items, make sure the guest cart item ID's don't clash
    $guestCartItems = array_map(function ($item) use ($guestCartItems) {
        return array_merge($item, [
            'id' => max(array_column($guestCartItems, 'id')) + 1 // my cart item ID's are an auto incrementing integer
        ]);
    }, $guestCartItems);
}

$userCart->add($guestCartItems);

$dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items');

if ($dbCart) $dbCart->delete();
```

This solution makes 2 events a little tightly coupled, but it is good enough for me. You could add some extra if's here and there just in case.

**N.B. I have not thoroughly tested this like with a newly registered user, so please use with caution.**

**Comment by esponges** [comment]
> $dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items'); // <- using DB storage for cart
> 
> if ($dbCart) $dbCart->delete(); // or clear from session
> 

Man great job! You saved me a lot ton of work. Had to make some research since I hadn't used Laravel listeners before but your solution worked out with lil adaptations to my code.

Last thing, `$dbCart` means you were storing Cart items into your database with a model, right? I'm not using any Cart model so I removed those two lines and all appears to be working fine.

**Comment by liamjcooper** [comment]
> > $dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items'); // <- using DB storage for cart
> 
> > 
> 
> > if ($dbCart) $dbCart->delete(); // or clear from session
> 
> > 
> 
> 
> 
> Man great job @liamjcooper! You saved me a lot ton of work. Had to make some research since I hadn't used Laravel listeners before but your solution worked out with lil adaptations to my code.
> 
> 
> 
> Last thing, `$dbCart` means you were storing Cart items into your database with a model, right? I'm not using any Cart model so I removed those two lines and all appears to be working fine.
> 
> 

@esponges Thanks! Glad to hear you were successful with this.

Yes I was storing cart content in the db, using the model example provided in docs. Not necessary to have that code there 😄

**Comment by gaiahub** [comment]
How are you doing this?  The `$session_id = \Session::getId();` changes during the login process and I cannot capture the guest users data.  Where are you placing this code?  I am trying unsuccessfully in `\app\Http\Controllers\Auth\LoginController.php`

**Comment by liamjcooper** [comment]
> How are you doing this?  The `$session_id = \Session::getId();` changes during the login process and I cannot capture the guest users data.  Where are you placing this code?  I am trying unsuccessfully in `\app\Http\Controllers\Auth\LoginController.php`

Please read my solution carefully, it uses Laravel's event and listeners functionality. You can capture the guest session ID in my sample PrepareCartTransfer listener code above.

**Comment by gaiahub** [comment]
@liamjcooper thank you for that!  I seem to be having 1 problem with `$dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items');`
error: `Class 'App\Cart' not found `

**Comment by liamjcooper** [comment]
> @liamjcooper thank you for that!  I seem to be having 1 problem with `$dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items');`
> 
> error: `Class 'App\Cart' not found `
> 
> 
> 
> If i change it to `$dbCart = \Cart::find(session('guest_cart.session') . '_cart_items');`
> 
> then error: `Call to undefined method Darryldecode\Cart\Cart::find() `

Those last 2 lines of code only apply if you're using a persistent storage such as a model to manage previous carts. If you do use a model for cart storage, this is used to delete the guest cart from the DB once it has been transferred.

**Comment by CODE-AXION** [comment]
> I managed to get this working by utilising Laravel's auth events.
> 
> In the EventServiceProvider's listen array, I listened for these 2 events:
> 
> ```
> \Illuminate\Auth\Events\Attempting::class => [
>     \App\Listeners\PrepareCartTransfer::class
> ],
> \Illuminate\Auth\Events\Login::class => [
>     \App\Listeners\TransferGuestCartToUser::class
> ]
> ```
> 
> In the attemping event, I have a listener that flashes the guest session ID and their cart into their session ready for the next page, like so:
> 
> ```
> if (\Auth::guest()) {
>     session()->flash('guest_cart', [
>         'session' => session()->getId(),
>         'data' => cart()->getContent() // i have a global cart() function in my app which sets the correct session
>     ]);
> }
> ```
> 
> Then in the login event, I use the flashed data to merge the items into the user cart. You could just replace the user's cart rather than merge it in to make your life easier but I decided to merge it in.
> 
> ```
> $userCart = cart()->session($event->user->id);
> $userCartItems = $userCart->getContent()->toArray();
> 
> $guestCart = session('guest_cart.data');
> $guestCartItems = $guestCart->toArray();
> 
> // my app does not require quantities so I can just add new items as cart lines regardless of 
> // duplicates. If your app needs to merge in duplicate product quantities, you can just make
> // the ID of the existing items you are adding the same as the matching items in the user's cart.
> // This library will automatically add in the relative quantity.
> // Or just wipe the user's cart and replace it entirely.
> if ($userCart->getContent()->isNotEmpty()) {
>     $maxUserCartId = max(array_column($userCartItems, 'id'));
> 
>     // user cart has items, make sure the guest cart item ID's don't clash
>     $guestCartItems = array_map(function ($item) use (&$maxUserCartId) {
>         return array_merge($item, ['id' => ++$maxUserCartId]);
>     }, $guestCartItems);
> }
> 
> if ($guestCart->isNotEmpty()) $userCart->add($guestCartItems);
> 
> $dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items'); // <- using DB storage for cart
> 
> if ($dbCart) $dbCart->delete(); // or clear from session
> ```
> 
> This solution makes 2 events a little tightly coupled, but it is good enough for me. You could add some extra if's here and there just in case.
> 
> **N.B. I have not thoroughly tested this like with a newly registered user, so please use with caution.**

where do you dispatch this event ? in the authenticated session controller or login request ?

**Comment by liamjcooper** [comment]
> > I managed to get this working by utilising Laravel's auth events.
> 
> > 
> 
> > In the EventServiceProvider's listen array, I listened for these 2 events:
> 
> > 
> 
> > ```
> 
> > \Illuminate\Auth\Events\Attempting::class => [
> 
> >     \App\Listeners\PrepareCartTransfer::class
> 
> > ],
> 
> > \Illuminate\Auth\Events\Login::class => [
> 
> >     \App\Listeners\TransferGuestCartToUser::class
> 
> > ]
> 
> > ```
> 
> > 
> 
> > In the attemping event, I have a listener that flashes the guest session ID and their cart into their session ready for the next page, like so:
> 
> > 
> 
> > ```
> 
> > if (\Auth::guest()) {
> 
> >     session()->flash('guest_cart', [
> 
> >         'session' => session()->getId(),
> 
> >         'data' => cart()->getContent() // i have a global cart() function in my app which sets the correct session
> 
> >     ]);
> 
> > }
> 
> > ```
> 
> > 
> 
> > Then in the login event, I use the flashed data to merge the items into the user cart. You could just replace the user's cart rather than merge it in to make your life easier but I decided to merge it in.
> 
> > 
> 
> > ```
> 
> > $userCart = cart()->session($event->user->id);
> 
> > $userCartItems = $userCart->getContent()->toArray();
> 
> > 
> 
> > $guestCart = session('guest_cart.data');
> 
> > $guestCartItems = $guestCart->toArray();
> 
> > 
> 
> > // my app does not require quantities so I can just add new items as cart lines regardless of 
> 
> > // duplicates. If your app needs to merge in duplicate product quantities, you can just make
> 
> > // the ID of the existing items you are adding the same as the matching items in the user's cart.
> 
> > // This library will automatically add in the relative quantity.
> 
> > // Or just wipe the user's cart and replace it entirely.
> 
> > if ($userCart->getContent()->isNotEmpty()) {
> 
> >     $maxUserCartId = max(array_column($userCartItems, 'id'));
> 
> > 
> 
> >     // user cart has items, make sure the guest cart item ID's don't clash
> 
> >     $guestCartItems = array_map(function ($item) use (&$maxUserCartId) {
> 
> >         return array_merge($item, ['id' => ++$maxUserCartId]);
> 
> >     }, $guestCartItems);
> 
> > }
> 
> > 
> 
> > if ($guestCart->isNotEmpty()) $userCart->add($guestCartItems);
> 
> > 
> 
> > $dbCart = \App\Cart::find(session('guest_cart.session') . '_cart_items'); // <- using DB storage for cart
> 
> > 
> 
> > if ($dbCart) $dbCart->delete(); // or clear from session
> 
> > ```
> 
> > 
> 
> > This solution makes 2 events a little tightly coupled, but it is good enough for me. You could add some extra if's here and there just in case.
> 
> > 
> 
> > **N.B. I have not thoroughly tested this like with a newly registered user, so please use with caution.**
> 
> 
> 
> where do you dispatch this event ? in the authenticated session controller or login request ?

The `Attempting` and `Login` events are built-in to Laravel, so they get dispatched automatically unless you have custom auth code - then you would have to dispatch those events yourself.

**Comment by CODE-AXION** [comment]
> 

Yeah I did tried this method and it worked but I didn't made the cart table soo ,will it work if I add Cart::add($some_variables) in the handle  method? 

Because it is shifting the session cart items to authenticated user cart ! Now only 1 thing is remaining saving that data into the database!

**Comment by liamjcooper** [comment]
> Yeah I did tried this method and it worked but I didn't made the cart table soo ,will it work if I add Cart::add($some_variables) in the handle method?
> 
> Because it is shifting the session cart items to authenticated user cart ! Now only 1 thing is remaining saving that data into the database!

Don't take my word for it but I think so? Just try it out and see if it works on your machine. I think Laravel could get a known users' session from wherever you store your session, as long as you haven't configured the session driver to be 'array'.
