### ISSUE TITLE
Condition lives on after removing

### ISSUE THREAD

**Issue by mjanssen** [darryldecode/laravelshoppingcart#26]
When a new condition is added using the Cartcondition like below, the discount is calculated over the price, which is good.
```
$discountCondition = new \Darryldecode\Cart\CartCondition([
        'name' => 'discount-code',
        'type' => 'discount-code',
        'target' => 'subtotal',
        'value' => $discountValue, // (-30%)
        'attributes' => [
            'code' => $code
        ]
]);

\Cart::condition($discountCondition);
```

But when a customer removes the discount code, and I remove the condition (`\Cart::removeCartCondition('discount-code');`), the condition is removed after the code is executed, but when I reload the page, the condition is still applied. The condition is also shown in the `\Cart::getConditions();` array.

Could you please take a look at it :)

**Comment by darryldecode** [comment]
Hi @mjanssen ,

I can't verify it, this seems to be working fine on my end. And all tests are passing.

```
Cart::add(array(
        array(
            'id' => 456,
            'name' => 'Sample Item 1',
            'price' => 67.99,
            'quantity' => 4,
            'attributes' => array()
        ),
        array(
            'id' => 568,
            'name' => 'Sample Item 2',
            'price' => 69.25,
            'quantity' => 4,
            'attributes' => array(
                'size' => 'L',
                'color' => 'blue'
            )
        ),
    ));

    var_dump(Cart::getConditions()); // --> array (size=0)
    var_dump(Cart::getTotal()); // --> 548.96

    $discountCondition = new \Darryldecode\Cart\CartCondition([
        'name' => 'discount-code',
        'type' => 'discount-code',
        'target' => 'subtotal',
        'value' => '-30%',
        'attributes' => [
            'code' => 'some-code'
        ]
    ]);

    Cart::condition($discountCondition);

    var_dump(Cart::getConditions()); // --> array (size=1)
    var_dump(Cart::getTotal()); // --> 384.272

    Cart::removeCartCondition('discount-code');

    var_dump(Cart::getConditions()); // --> array (size=0)
    var_dump(Cart::getTotal()); // --> 548.96

    Cart::clear();
```

**Comment by mjanssen** [comment]
Allright! So the condition has to be set every time I reload the page? I thought it was set like some session, just like the cart. If you can verify that it's not stored by session or whatsoever, than I'll just update my system.

**Comment by darryldecode** [comment]
Hello @mjanssen ,

That's weird as it is working correctly on my installations. Yes conditions and cart Items are stored in session. You can verify it by dumping ```Session::all();```

**Comment by mjanssen** [comment]
Dumping all my session results in:

(Yeah, used "omg" for a discount code... >.<)
```
"4yTlTDKu3oJOfzD_cart_conditions" => CartConditionCollection {#277 ▼
    #items: array:3 [▼
      "Discount: omg" => CartCondition {#279 ▶}
      "discount-code" => CartCondition {#280 ▶}
      "transfer-costs" => CartCondition {#281 ▶}
    ]
  }
  "4yTlTDKu3oJOfzD_cart_items" => CartCollection {#282 ▶}
```

When I place `\Cart::removeCartCondition('Discount: omg');` before dumping the session, the result is

```
"4yTlTDKu3oJOfzD_cart_conditions" => CartConditionCollection {#339 ▼
    #items: array:2 [▼
      "discount-code" => CartCondition {#280 ▶}
      "transfer-costs" => CartCondition {#281 ▶}
    ]
  }
  "4yTlTDKu3oJOfzD_cart_items" => CartCollection {#282 ▶}
```

Which seems okay. Nevertheless, when I remove the line above my session dump (that would be the removeCartCondition line), the session dump result prints:

```
"4yTlTDKu3oJOfzD_cart_conditions" => CartConditionCollection {#277 ▼
    #items: array:3 [▼
      "Discount: omg" => CartCondition {#279 ▶}
      "discount-code" => CartCondition {#280 ▶}
      "transfer-costs" => CartCondition {#281 ▶}
    ]
  }
  "4yTlTDKu3oJOfzD_cart_items" => CartCollection {#282 ▶}
```

As you can see, the "Discount: omg" is back again. In fact, the code that created the condition is commented out, and not even called in the system, so it's not added again. Any idea how this can happen?

**Comment by darryldecode** [comment]
Because,

the ```Cart::condition($discountCondition);```
is on top of the ```\Cart::removeCartCondition('Discount: omg');``` on your code

thus, ```Cart::condition($discountCondition);``` will always be executed when you refresh the page and will keep it on adding the condition..

In a real world application, these two are separately executed..

**Comment by mjanssen** [comment]
The `Cart::condition($discountCondition);` is only executed once, when the customer provides a valid discount code. I think I managed to fix the problem by moving everything to a separate class that handles everything.

It looks like it's working correctly right now. Thanks for your responses tho!! :)

If something strange pops up again, I'll contact you again. Closing issue for now.
