### ISSUE TITLE
Adding Sizes and Variations To Selected Products 

### ISSUE THREAD

**Issue by Quadrifolo** [darryldecode/laravelshoppingcart#260]
Sorry , I'm fairly new to Laravel and got the cart to work but wasn't sure how to go about adding sizes and variations to the cart so that i can store them in an order since I am using this package for an ecommerce site could anyone please assist

**Comment by lostcause** [comment]
You can use attributes for this. Here's a snippet of code from one my projects:

`        \Cart::add($uniqueId, $product->name, $product->getFullPrice($stock->pivot->stock), 1, [
            'id'          => $product->id,
            'image'       => $request->get('image'),
            'url'         => $product->getRoute(['color' => $request->get('variant')]),
            'category_id' => $product->category_id,
            'size'        => [
                'id'    => $size->id,
                'value' => $size->value,
            ],
            'variant' => [
                'id' => $variant->id,
            ],
            'color'       => [
                'id'    => $color->id,
                'value' => $color->value,
            ],
            'weight'      => $product->weight,
            'stock'       => $stock->pivot->stock,
        ]);`

You can use the attributes to hold any extra info you need, and then save it in the database once the order is finished.

**Comment by Quadrifolo** [comment]
Hi thank you for your response did you declare all of these variables above in your code ?

**Comment by lostcause** [comment]
Yes, this is the whole method:

```php
    public function store(Request $request, Product $product)
    {
        $size    = SizeValue::find($request->get('size'));
        $variant = ProductVariation::with(['combinations', 'sizes'])->find($request->get('variant'));
        $color   = AttributeValue::find($variant->combinations()->first()->attribute_value_id);
        $stock   = $variant->sizes()->where('size_value_id', $size->id)->first();

        $uniqueId = sha1("{$product->id}-{$color->id}-{$size->id}");

        \Cart::add($uniqueId, $product->name, $product->getFullPrice($stock->pivot->stock), 1, [
            'id'          => $product->id,
            'image'       => $request->get('image'),
            'url'         => $product->getRoute(['color' => $request->get('variant')]),
            'category_id' => $product->category_id,
            'size'        => [
                'id'    => $size->id,
                'value' => $size->value,
            ],
            'variant' => [
                'id' => $variant->id,
            ],
            'color'       => [
                'id'    => $color->id,
                'value' => $color->value,
            ],
            'weight'      => $product->weight,
            'stock'       => $stock->pivot->stock,
        ]);

        self::updateCartCondition();

        return view('site.cart._partials.side');
    }
```

**Comment by Quadrifolo** [comment]
Alright Perfect Thank you I have been able to implement it now
