### ISSUE TITLE
Cart not adding items

### ISSUE THREAD

**Issue by nudlez** [darryldecode/laravelshoppingcart#264]
Hello, 

First off, thank you for this, it helped me a lot! Also, please excuse my english, I will try and explain this as clearly as I can. 

I have seem to encounter an issue wherein the cart is not adding additional items, it can only save/hold 1 item. When I try to add another, the previously saved item on the cart gets overwritten with the new one and the cart shows only one item. I followed your instructions, using session(user's id), adding unique cart id, etc... Here's my code so far:
```
public function add(Request $request, $id){
        $menu = Menu::find($id);
        $cart_id = rand(1, 500);
        \Cart::session($this->userID())->add($cart_id, $menu->name, $menu->price, $request->qty, array('image'=>$menu->image));
        
        $cart = \Cart::session($this->userID())->getContent();
        return dd($cart);
    }

```
The code above is only for testing purposes as I do not seem to work around this issue.
 
I am using Laravel 7 by the way and also Fedora 32. Does this have something to do with my localhost server? If so, do you have any suggestions?

Again, I thank you for this and wish you a great day

**Comment by nudlez** [comment]
Figured it out. Thanks!

**Comment by grcasanova** [comment]
Hi, how did you solve the issue? I'm facing the same problem. Thanks!

**Comment by nudlez** [comment]
@ grcasanova  Oh, it was due to my userID() function, it was not returning the currently logged in user's ID for some reason. Fixed it by using Auth::user()->id directly instead and it seemed to work.
