### ISSUE TITLE
Class 'App\DBStorage' not found 

### ISSUE THREAD

**Issue by gaiahub** [darryldecode/laravelshoppingcart#267]
** resolved
your sample is missing
`use Darryldecode\Cart\CartCollection;`

Error highlights:
`$storage = $storageClass ? new $storageClass() : $app['session'];`

I have \app\DBStorage.php

`class DBStorage {

    public function has($key)
    {
        return DatabaseStorageModel::find($key);
    }

    public function get($key)
    {
        if($this->has($key))
        {
            return new CartCollection(DatabaseStorageModel::find($key)->cart_data);
        }
        else
        {
            return [];
        }
    }

    public function put($key, $value)
    {
        if($row = DatabaseStorageModel::find($key))
        {
            // update
            $row->cart_data = $value;
            $row->save();
        }
        else
        {
            DatabaseStorageModel::create([
                'id' => $key,
                'cart_data' => $value
            ]);
        }
    }
}`

**Comment by 0test** [comment]
Hi. How you fix it?
