### ISSUE TITLE
Updating quantity issue

### ISSUE THREAD

**Issue by Blum** [darryldecode/laravelshoppingcart#27]
Hello,
first of all, thank you for the nice implementation.

I was quite surprised that the cart quantity update method actually adds quantity. 
Is there a way to easy update the quantity with a certain value, e.g. if the quantity is 5 to make it 7 right away, and not 5+7=12?

Thanks

**Comment by dannyvankooten** [comment]
:+1: Agreed, would be neat if we can just set the cart quantity directly.

**Comment by darryldecode** [comment]
Hello, sorry for the late response. I've been out of town lately. I will look into this shortly..

**Comment by darryldecode** [comment]
Hi all, this is now updated. Please see commit 044317eb04ef01a34e3df8acb87a53efe7afd2eb
See the docs on update quantity section..

Thank you for your time :+1:

**Comment by Blum** [comment]
Awesome! Thank you!
