### ISSUE TITLE
Cart only updates the quantity and not the price

### ISSUE THREAD

**Issue by whoami15** [darryldecode/laravelshoppingcart#276]
### Cart only updates the quantity and not the price

`Cart::session($user->id)->add($product->id, $product->title, $product->price, 1, array())->associate($product);`

If you **add to cart the same item**, it only update its **quantity** and not the **price**, 
the price should be multiplied by the current quantity.

here's a dump
as you can see the `price` is still 120 even if the `quantity` is 2
```php
items: array:7 [
    "id" => 1
    "name" => "Product name"
    "price" => 120
    "quantity" => 2
    "attributes" => Darryldecode\Cart\ItemAttributeCollection {#471}
    "conditions" => []
    "associatedModel" => App\Product {#472}
]

**Comment by TheRealJanJanssens** [comment]
Don't know if you found the explanation yourself yet but this is the intended behaviour. The calculation price * quantity will be made in getSubTotal() or getTotal() functions. If you want to display this separately you have to do the calculation yourself.
`
foreach(Cart::getContent() as $item){
  echo $item->price * $item->quantity
}
`
