### ISSUE TITLE
how i can use it for REST API

### ISSUE THREAD

**Issue by cinonu** [darryldecode/laravelshoppingcart#277]
i am not able to use it for rest api's if there is another way please tell me

**Comment by dennernavarro** [comment]
What is the real issue?

**Comment by henryejemuta** [comment]
> i am not able to use it for rest api's if there is another way please tell me

Using with REST require you to explicitly specify the session ID on cart \Cart::session($userID) the user ID unique bind user to their respective cart... 

My implementation was quite straightforward...
While using the API via frontend app when the user is unauthenticated I generate a unique session ID to uniquely identify the cart...
Then, using events I listen for before Auth to tie the unique session ID to the user attempting to authenticate...
If authentication is successful I update cart session ID to the authenticated user unique ID \Cart::session($userID) 
Then add previous cart content to the authenticated user cart and clear the previous cart...

Do let me know if you need further clarification

**Comment by cinonu** [comment]
i got it thanks a lot
