### ISSUE TITLE
How add one item twice with different attributes ?

### ISSUE THREAD

**Issue by vilbur** [darryldecode/laravelshoppingcart#28]
Hello,
I would like add the same item, but with different attributes.
e.g.: 
item in cart has attribute = ['color' => 'red'],
and I would like to add the same item with attribute = ['color' => 'blue'].

I except two items with different arguments in cart, but old item`s attributes are overwritten with new attributes and quantity is updated to 2. 
I didn't find this in documentation, maybe I missed it.
Is there any way how to achieve this, please ?

...Thank You.

**Comment by darryldecode** [comment]
Hello @vilbur,

You cannot add two items in the cart with the same ID as it will assume that the Item/Product you are trying to add on the cart is the same product and would cause duplicate so it will increment its quantity instead.. If you want, you have to give it a unique ID and put the Products ID on the attributes instead..

Eg. 

```
Cart::add(array(
    'id' => '884785917232', // some unique ID here
    'name' => 'Sample Item',
    'price' => 67.99,
    'quantity' => 4,
    'attributes' => array(
         'product_id' => '145'
    )
));
```

**Comment by darryldecode** [comment]
I see the problem with your scenario. I will probably work on this on the next update.. Thanks!

**Comment by vilbur** [comment]
Thank you, it`s clear now.
 I thought, that it will be like that. Maybe You can highlight it in documentation, because it look like database ID, more than cart item ID.

I have second question for you ;)
ItemAttributeCollection turns into array when I try to update attributes.

eg:
```
    $item = [
         'id'         => 1,
         'name'       => 'test',
         'price'      => '999',
         'quantity'   => 1,
         'attributes' => [
            'product_id'=> 1,
            'test' => 'toUpdate',
         ]
    ]; 
  \Cart::update( 1, $item );

```
DUMPED RESULT IS:
```
    ItemCollection {
        #items: array (
            "id" => 1
            "name" => "test"
            "price" => "999"
            "quantity" => 6
            "attributes" => ARRAY (
                "product_id" => 1,
                "test" => "updated"
            )
             "conditions" => []
        )
    }
```
BUT what I expect and how original object looks like is:
```
    ItemCollection {
        #items: array (
            "id" => 1
            "name" => "test"
            "price" => "999"
            "quantity" => 6
            "attributes" => ItemAttributeCollection {
                  #items: array (
                       "product_id" => 1,
                       "test" => "updated"
                )
            }
             "conditions" => []
        )
    }
```

Quantity, price etc. work very well, but attributes returns array.
 Am I doing something wrong? Or should I remove item and add it again ?

Thanks for package and your reply.

**Comment by darryldecode** [comment]
Hi @vilbur,

Thank you for the heads up on this. This is now updated 044317eb04ef01a34e3df8acb87a53efe7afd2eb

Thank you for your time! :+1:
