### ISSUE TITLE
cart condition on subtotal

### ISSUE THREAD

**Issue by debuEkodus** [darryldecode/laravelshoppingcart#281]
I have applied a tax percentage condition on subtotal. Condition is on cart basis. I want to get the subtotal price without the conditions applied. Also I would like to get the tax calculated value upto 2 decimals , How to achieve that?

**Comment by TheRealJanJanssens** [comment]
You can get the subtotal without any conditions with this:
Cart::getSubTotalWithoutConditions();

To get only the calculated value of a certain condition you can use this:
Cart::getCondition('VAT')->parsedRawValue

Does this solve your issue?

**Comment by debuEkodus** [comment]
Cart::getSubTotalWithoutConditions();
This worked. Thank you for the response.
However the other one below didn't worked in my cart blade.
Cart::getCondition('VAT')->parsedRawValue

**Comment by TheRealJanJanssens** [comment]
Did you change 'VAT' in the getCondition() function to the name you have set for your condition?

**Comment by debuEkodus** [comment]
Yes I changed.

**Comment by TheRealJanJanssens** [comment]
Maybe I'm overlooking something.
Can you paste your code?

**Comment by debuEkodus** [comment]
$subTotal=\Cart::session(auth()->user()->id)->getSubTotalWithoutConditions();
$condition=\Cart::session(auth()->user()->id)->getCondition('Tax');
$condition->getCalculatedValue($subTotal);//This gave me the expected output

**Comment by debuEkodus** [comment]
Also can you help me one more thing I am stuck with.
I have one item based condition and one cart value based condition (The tax condition above).
Suppose, I have an item with $10 and after adding item based condition the price is $15. Now when I apply the tax condition then it should get applied to $15 but it is getting applied to $10 which not I am not expecting. Please help with this.

**Comment by TheRealJanJanssens** [comment]
Ow yeah.. my bad ;)
parsedRawValue doesn't indeed give you the calculated value like $condition->getCalculatedValue() does.

For your last issue does this happen with getSubTotal() and getTotal()?

**Comment by debuEkodus** [comment]
I just checked the calculation. It seems ok to me. But when I call getSubTotal() it displays the total price with the condition whereas I just want to show the item price + the item based condition i.e. $15. Also When I checked the getCalculatedValue() it shows me the calculation for only item price & not item + item based condition. Please check below the outputs for better understanding.

Current output:
ItemPrice: $100
ItemCondition: $103
Subtotal: $109.82 (if used getSubTotal() & $100 if used getSubTotalWithoutConditions() )
Tax @6.625% : $ 6.625
Total: $109.82

Expected Output:
ItemPrice: $100
ItemCondition: $103
Subtotal: $103
Tax @6.625% : $ 6.823
Total: $109.82

**Comment by TheRealJanJanssens** [comment]
Is your tax condition set on subtotal or total?
Can you maybe copy your code so I can take a look?

**Comment by debuEkodus** [comment]
Tax condition is set on subtotal.

**Comment by TheRealJanJanssens** [comment]
> Tax condition is set on subtotal.

Try to set it to total. Normally that should give you the expected output.

**Comment by debuEkodus** [comment]
> output

Actually the tax is always to be applied only on subtotal i.e. item x itemQty or itemWithCondition x itemQty. I have updated the previous answer with my code. Kindly check.

**Comment by TheRealJanJanssens** [comment]
If I understand it correctly you need this?

Subtotal: the sum of all items with the applied item conditions
Tax: calculated value of the tax condition on subtotal
Total: all items and conditions applied

**Controller**
```
$itemcondition= new \Darryldecode\Cart\CartCondition(array(
    'name' => 'misc',
    'type' => 'misc',
    'value' => '+3'
));

$item=Item::find(12);

\Cart::session(auth()->user()->id)->add(array(
    'id' => 12,
    'name' => 'pname',
    'price' =>100,
    'quantity' => 1,
    'conditions' => $itemcondition
));

$cartcondition = new \Darryldecode\Cart\CartCondition(array(
    'name' => 'Tax',
    'type' => 'tax',
    'target' => 'total', <-changed this to total so it will not be applied when calling for subtotal
    'value' => '6.625%'
));

\Cart::session(auth()->user()->id)->condition($cartcondition);
```

**Blade**
```

$subTotal=\Cart::session(auth()->user()->id)->getSubTotal(); <- removed the WithoutConditions so the item conditions will apply on subtotal
$condition=\Cart::session(auth()->user()->id)->getCondition('Tax');

Subtotal: {{ $subTotal }}
Tax: {{ $condition->getCalculatedValue($subTotal) }}
Total: {{ Cart::session(auth()->user()->id)->getTotal() }}

```

Which would output
**Subtotal:** 103.00
**Tax:** 6.82375
**Total:** 109.82

if you want the individual item prices displayed you can call this

```

$items = Cart::getContent();
foreach($items as $item){
    $item->getPriceSum(); // gets sum of price * quantity without conditions
    $item->getPriceWithConditions() // gets price single item with conditions
    $item->getPriceSumWithConditions() // gets sum of price * quantity with conditions
}

```

**Comment by debuEkodus** [comment]
Thanks for the solution. I guess I tried too the same thing but in a different way.  
I added a new function to the package. Please find it below:
````
public function getSubTotalWithoutCartConditions($formatted = true)
    {
        $cart = $this->getContent();

        $sum = $cart->sum(function ($item) {
            return $item->getPriceSumWithConditions();//item conditions are added
        });

        return Helpers::formatValue(floatval($sum), $formatted, $this->config);
    }
````

**BLADE**
