### ISSUE TITLE
Show the cart Total Quantity on all pages

### ISSUE THREAD

**Issue by LouisLecouturier** [darryldecode/laravelshoppingcart#298]
Hey ! I was just wondering if there was a way to show the number of items in the cart as a badge on all pages and if so, how can I do that please ?

**Comment by jaaferklila** [comment]
I have the same issue

**Comment by LouisLecouturier** [comment]
> I have the same issue

I found out how to do it !

Simply write in your html 
`
{{ Cart::session($sessionKey)->getContent()->count() }}
`

I still have to find a way to retrieve that number when a user is logged in ^^
