### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by giovannefc** [darryldecode/laravelshoppingcart#3]
Hi,
Its leave the whole conditions of the cart in session? Because I set a condition and on checkout I lose the getConditions() values.

Another thing, I tried something like $condition->getValue ()-> first () without the need to use a foreach. Is there any way?

Thank you.

**Comment by darryldecode** [comment]
Hi @giovannefc currently conditions are just stored as an array. So the conditions should be applied on the very last step of your checkout that is ready to be sent to any payment gateway. But I guess it should be persisted on session as well so it will be flexible as it should. I will work on this. Thank you for your time.

**Comment by darryldecode** [comment]
done be0b056cd842f64ecb6bd61164e29aebd302a14d
