### ISSUE TITLE
Cart::update()

### ISSUE THREAD

**Issue by redkowloon** [darryldecode/laravelshoppingcart#30]
Hi , 

Cart::update(456, array(
  'quantity' => array(
      'relative' => false,
      'value' => 5
  ),
));

give me this : 

ErrorException in Cart.php line 204:

preg_match() expects parameter 2 to be string, array given

**Comment by darryldecode** [comment]
Hi @redkowloon ,

Sorry but I was not able to reproduce this error. Can you please update your cart and let me know if this error still exist? Thanks!
