### ISSUE TITLE
Cart::getTotal() in view

### ISSUE THREAD

**Issue by subdesign** [darryldecode/laravelshoppingcart#43]
When I want to echo out the total value in the view, I get the following error:
```php
ErrorException
Trying to get property of non-object.. {view file name}
/­vendor/­darryldecode/­cart/­src/­Darryldecode/­Cart/­Cart.php510
Line: $originalPrice = $item->price;
```
Of course I have some items in the cart, and all items have price set.

```php
CartCollection {#401 ▼
  #items: array:2 [▼
    21 => array:6 [▼
      "quantity" => 6
      "id" => "21"
      "name" => "******************"
      "price" => 7800.0
      "attributes" => ItemAttributeCollection {#341 ▶}
      "conditions" => []
    ]
    31 => array:6 [▼
      "quantity" => 6
      "id" => "31"
      "name" => "**************"
      "price" => 1.0
      "attributes" => ItemAttributeCollection {#342 ▶}
      "conditions" => []
    ]
  ]
}
```
EDIT: its not always, when I clear the cart, no error happens. It's something with adding to the cart...

EDIT 2: some way one of my item differs from others:
```
CartCollection {#386 ▼
  #items: array:2 [▼
    21 => ItemCollection {#341 ▶}
    31 => array:6 [▶]
  ]
}
```
this is why error happens.. any idea?

EDIT 3:
When I constantly add, remove items to the cart, sometimes one of the items randomly will be saved as array, and not as ItemCollection. Of course I use the same code all the way..
```
CartCollection {#435 ▼
  #items: array:4 [▼
    21 => ItemCollection {#341 ▶}
    27 => ItemCollection {#343 ▶}
    22 => ItemCollection {#345 ▶}
    20 => array:6 [▶]
  ]
}
```

**Comment by darryldecode** [comment]
Hello @subdesign ,

That is weird. The CartCollection should contain an array of ItemCollection Object, not an array. I see that some are added as array that is why when you called ```$item->price``` throws as error.. What are you using to add item on cart that results to array?

**Comment by subdesign** [comment]
I add items with jquery ajax like:
```php
    public function addItem()
    {
        if (Request::ajax()) {

            Cart::add([
                'id'         => Request::input('id'),
                'name'       => Request::input('name'),
                'price'      => Request::input('price'),
                'quantity'   => Request::input('count'),
                'attributes' => []
            ]);

            $cartCollection = Cart::getContent();

            return Response::json(['data' => ['itemsCount' => $cartCollection->count()]]);
        }
    }
```

**Comment by darryldecode** [comment]
Sorry I am really having problem replicating your issue. Can you elaborate more the process step by step when an item is added as array instead of ItemCollection Object. Thanks!

**Comment by subdesign** [comment]
Currently no idea what happens, I do things the way I read in the docs. Maybe the ajax calls can disturb some way the code? 
I'll investigate the code step by step soon. If you have idea what/how to debug in this case I appreciate it!

**Comment by subdesign** [comment]
changing this line in Cart.php 's __update()__ method 
```php
$cart->put($id, $item);
```
to
```php
$cart->put($id, new ItemCollection($item));
```
solved my problem.

**Comment by darryldecode** [comment]
hi @subdesign , that's weird because before the ``update()``` method can be triggered, the item should be added first which triggers ```addRow()``` which had the same code that you add:

```
protected function addRow($id, $item)
    {
        $cart = $this->getContent();
        $cart->put($id, new ItemCollection($item));
        $this->save($cart);
    }
```

So when the ```update()``` is triggered, you will see there's a code:
``` $item = $cart->pull($id);``` that pulls the item and it should return an instance of ItemCollection
but seems to return to you as an array so when you add this code ```$cart->put($id, new ItemCollection($item));``` on the ```update()``` method, it solves your issue.

But anyway, I think we can just add that..

**Comment by darryldecode** [comment]
@subdesign , can you do a PR and add that? also it's good to check first if the ```$item``` is already an instance of ItemCollection, something like:

```
if( ! $item instanceof ItemCollection )
{
    $cart->put($id, new ItemCollection($item));
}
else
{
    $cart->put($id, $item);
}
```

Thanks!

**Comment by subdesign** [comment]
I tried to make a pull request but the __Create pull request__ button is grayed out. Btw above addition could be good, strange that it's only me who meets this situation and no others :)
