### ISSUE TITLE
Ability to fetch the Monetary Value from Cart Condition

### ISSUE THREAD

**Issue by Sladewill** [darryldecode/laravelshoppingcart#5]
Could you add the ability to fetch the actual value from the condition rather than what you supply it:

for example:

Name | Value
-------- | --------------
| cart sub total | £10 |
| vat @ 20% | £2 |
| total | £12  |

Currently when you do $condition->getValue() it only returns the value you supplied in the condition.

```php
// add condition single condition
$condition = new CartCondition([
	'name'		=> 'VAT 20%',
	'type'		=> 'tax',
	'target'	=> 'total',
	'value'		=> '20%',
]);
```

What we really need is another method like $condition->getCalculateValue() will return the value that targets the sub total, or whatever value you have applied the condition to.

**Comment by darryldecode** [comment]
Hi,

there is a new tag release, please update your version and see changelogs. 
With regarding your issue, you do it with:

```php
// add item
Cart::add(array(
  array(
      'id' => 456,
      'name' => 'Sample Item 1',
      'price' => 10,
      'quantity' => 1,
      'attributes' => array()
  )
));

// add the condition
$condition = new \Darryldecode\Cart\CartCondition(array(
        'name' => 'VAT 20%',
        'type' => 'tax',
        'target' => 'subtotal',
        'value' => '20%',
));

// get cart total
$total = Cart::getTotal();
```

**Comment by Sladewill** [comment]
I'm already aware of that, I mean the total of that specific condition.

**Comment by darryldecode** [comment]
Honestly, I don't understand why you would need to do that. Since there's only one "total value" and that is the calculated value of all items on the cart with all of the added conditions.

**Comment by Sladewill** [comment]
If your iterating outputting the conditions to show a break down then you would need the values for example.

Name | Value
-------|---------
Sub Total | £10.00
VAT | £2.00
Delivery | £4.00
Total | £16.00

**Comment by darryldecode** [comment]
Hi @Sladewill ,

Is there any difference in doing it like so,

```php
// get sub total
$subTotal = Cart::getSubTotal();

// get cart conditions
$cartConditions = Cart::getConditions();
foreach($cartConditions as $condition)
{
    $condition->getTarget(); // the target of which the condition was applied
    $condition->getName(); // the name of the condition
    $condition->getType(); // the type
    $condition->getValue(); // the value of the condition
}

// get total
$cartTotal = Cart::getTotal();
```

Sorry, let me know if I am missing something here. Thanks!

**Comment by Sladewill** [comment]
When you use $condition->getValue(); it returns 20% for example rather than a figure like £2.00 it needs another function to run the calculation to the sub total.

**Comment by darryldecode** [comment]
yes you got point. We'll figure this out. Thanks @Sladewill !

**Comment by darryldecode** [comment]
Hello @Sladewill , see a8d7b2880544142552f07abbb397841b973fc591. There's also a new tagged version.
