### ISSUE TITLE
[Laravel 5.2] Class 'Cart' not found

### ISSUE THREAD

**Issue by dasaco** [darryldecode/laravelshoppingcart#53]
Hello,

Code in config/app.php

`'providers' => [

```
    Darryldecode\Cart\CartServiceProvider::class,        

],

'aliases' => [

    'Cart'      => Darryldecode\Cart\Facades\CartFacade::class,

],`
```

In Controller

tried Cart::add() got error **Class 'Cart' not found**

tried \Cart:add() got the same error

In header I used both

`use Cart;` 

and `use Darryldecode\Cart\Facades\CartFacade;` with this I got another error:

**Class 'App\Http\Controllers\Cart' not found**

tried 'use Darryldecode\Cart\Cart;' as well. Same error

**Comment by pavosoftware** [comment]
I had the same issue. Try adding:

`use Darryldecode\Cart\Facades\CartFacade as Cart;`

**Comment by mucyomiller** [comment]
i found that this problem can be cause by forgeting to clear cache configuration 
whenever you have this error do php artisan config:cache to clear old one and make new cached config
or use can register this package serviceprover right in routes.php 
App::register('Darryldecode\Cart\CartServiceProvider');

**Comment by AtikRahman12** [comment]
![screenshot_1](https://user-images.githubusercontent.com/35407745/48758359-ffdc2800-ecc9-11e8-9e36-685dd62e893b.png)
How can i solve this?
