### ISSUE TITLE
Sum value of individual item (quantity * price).

### ISSUE THREAD

**Issue by giovannefc** [darryldecode/laravelshoppingcart#6]
One idea:

Would put a field with the sum total of each item (quantity * price).

Example:

Cart::get($itemId);

[id] => 23
[name] => Item Name
[price] => 5.00
[quantity] => 3
[sum] => 15.00

Thank you!

**Comment by Sladewill** [comment]
+1 would be nice.

**Comment by darryldecode** [comment]
Hello, see a8d7b2880544142552f07abbb397841b973fc591. there's tagged version also.
