### ISSUE TITLE
Item price lower than zero?

### ISSUE THREAD

**Issue by junkystu** [darryldecode/laravelshoppingcart#60]
Hi,

I've noticed that if you add an item with a condition which ends up substracting more than the item's price, the item price ends up negative (e.g. price 15, value -20 results with -5 product price). Is that something that should be allowed? In my case, I would never want a negative product price. Please let me know and I can make a PR.

Test code:

    $product = [
        'id' => 123,
        'name' => 'Sample Item 1',
        'price' => 15,
        'quantity' => 1,
        'conditions' => new \Darryldecode\Cart\CartCondition([
            'name' => 'Substract 20',
            'type' => 'shipping',
            'target' => 'item',
            'value' => '-20',
        ]),
    ];

    \Cart::add($product);

    dd(\Cart::getTotal()); // -5

**Comment by darryldecode** [comment]
Hi @junkystu, yes that shouldn't be. Feel free to do a PR :+1:
