### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ebisbe** [darryldecode/laravelshoppingcart#63]
Is this project still maintained?

**Comment by darryldecode** [comment]
hello @ebisbe , yes but really busy this few weeks. Feel free to do PR. Thanks!

**Comment by ebisbe** [comment]
Nice! For the moment I'm just using it because it's working perfectly.

**Comment by AquaHuang** [comment]
I cannot do composer update
Problem 1,cannot find version ex 1.0.0
Problem2, about illuminate
Something I missing

**Comment by AquaHuang** [comment]
Thanks,
Found solution~
