### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by oad-dwarf** [darryldecode/laravelshoppingcart#81]
Laravel 5.4 removed the Application::share() function, so now the cart breaks with this error:

Call to undefined method Illuminate\Foundation\Application::share()  

 See https://laravel.com/docs/5.4/upgrade and "share method removed".

**Comment by Blum** [comment]
:+1:

**Comment by frezno** [comment]
i placed a pull request for this

**Comment by tomfordweb** [comment]
5.4 support would be nice!

**Comment by krisskerr** [comment]
Really could do with this library being made compatible for Laravel 5.4...

**Comment by frezno** [comment]
you guys can add my fork as repository to your composer.json file to make it work.
After adding it, run `composer update` and the pull requests will be added as well:

excerpt of the modified composer.json:
`

    "type": "project",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/frezno/laravelshoppingcart"
        }
    ],
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "darryldecode/cart": "dev-master"
    },
`

**Comment by SeanWhelan** [comment]
@frezno Nice! thanks

**Comment by frezno** [comment]
now you can use my fork for a no-brainer installation as well
https://github.com/frezno/freznocart

**Comment by darryldecode** [comment]
Release for laravel 5.4 support: https://github.com/darryldecode/laravelshoppingcart/releases/tag/3.0.0
Base on this PR: https://github.com/darryldecode/laravelshoppingcart/pull/82
