### ISSUE TITLE
Get Item Conditions sums

### ISSUE THREAD

**Issue by t2thec** [darryldecode/laravelshoppingcart#84]
Hey, thanks for the fantastic package. Its really well thought out.

I've been going through the source code and trying to figure out if this is possible?

In the UK, tax can be applied to some items, but not others. So I have been adding a tax condition to the item.

I'd like to be able to do something like: `$item->getItemConditionSumByType('tax')` which would then fire out the total of the all items that have tax applied.

Is there anything like that available or a way to achieve this? If not, are you open to pull request for such feature?

Thanks

**Comment by aalyusuf** [comment]
I don't think there is such function, you can either
1. Loop through items, do a ```getPriceSum``` and ```getPriceSumWithConditions``` and subtract them.
2. Subtract ```Cart::getSubTotalWithoutConditions()``` from ```Cart::getSubTotal()``` .. keep in mind that this would only work if you don't have any other types of conditions (discounts etc)

**Comment by t2thec** [comment]
Thanks @aalyusuf. Thats what I had figured too. I think I am going to fork and build what I need.

Thanks again bud.
