### ISSUE TITLE
Can I use different session storages for different cart instances?

### ISSUE THREAD

**Issue by Blum** [darryldecode/laravelshoppingcart#89]
I have a cart, I also have a favorites list. For the cart I'm using redis session storage (default session storage). But for the favorites list I want to use some long-living session storage with its own config file, database driver with long cookie lifetime.

I easy manage to make a different cart instance, but it is using the same session storage.

So, do you think it is possible? Any ideas?

Thank you

**Comment by darryldecode** [comment]
Hi refer to this discussion: https://github.com/darryldecode/laravelshoppingcart/issues/67

**Comment by darryldecode** [comment]
![image](https://cloud.githubusercontent.com/assets/5498919/25703350/1527c834-308a-11e7-9737-e46135f4f699.png)
You can put a different storage right

**Comment by Blum** [comment]
Yes but.. still struggling to make it work for different than the default storage. Did somebody tried that in practice?

**Comment by darryldecode** [comment]
Hi, that shoud be just fine, you can use put any session handler you want there. Only thing it needs is the methods ```put($key,$val), has($key), get($key)```

See the sessionMock in this test:
![image](https://cloud.githubusercontent.com/assets/5498919/25703988/b08115f4-308c-11e7-9c7f-83294d256a55.png)
And then:
![image](https://cloud.githubusercontent.com/assets/5498919/25704101/08780ac4-308d-11e7-9720-40b33346118a.png)

So, your session class should contain that three methods, and the cart doesn't care what's the engine on you use for storing. That should give you a good idea to start. cheers!

**Comment by Blum** [comment]
Thank you very much, that helped a lot!
Cheers

**Comment by darryldecode** [comment]
Cool. Glad that helps :)

**Comment by codeitlikemiley** [comment]
is using redis possible for the session? 
have anyone tried any approach how to use this package with a redis session storage
