### ISSUE TITLE
Ability to associate a product model to an item

### ISSUE THREAD

**Issue by clemquinones** [darryldecode/laravelshoppingcart#92]
I was wondering, would it be nice if we can associate a model for the item? It wouldn't necessary to make an eloquent query again if the product entity could access through our Cart instance?
Something like this:

```php
$item = Cart::add(123, 'Product Sample', 100.99, 2, $attributes)->associate(Product::class);

// This will return an App\Product instance
$product = $item->model;

// With this, we may perform accessing its relationship to other models and other model stuff
$product->category->name;

```

Looking forward to seeing this on the project.

**Comment by darryldecode** [comment]
Hi @clemquinones , that's a good feature actually. But didn't have the chance to work on it. I'll look into that idea again. PR are also welcome. Thanks 👍

**Comment by alhaji-aki** [comment]
Is this done?

**Comment by kgp43** [comment]
Any update on this?
