### ISSUE TITLE
Add to Cart without redirect to Cart

### ISSUE THREAD

**Issue by lampsoft** [darryldecode/laravelshoppingcart#93]
Please How can I add to cart without redirecting to Cart. I just want my Product to be in cart if I click on Add to Cart instead of Redirecting me to cart?

**Comment by bloggervista** [comment]
That depends on your setup. Its you who redirect to cart not this package bro. You can just use Cart::add() and it is fine :)

**Comment by malaymehta** [comment]
@darryldecode This can be closed as well
