### ISSUE TITLE
getTotalQuantity() working bad

### ISSUE THREAD

**Issue by j574144** [darryldecode/laravelshoppingcart#94]
For advance, this is great work from you. Thanks!!! 

When I try add a same item, the cart do a great work to prevent duplicate items in array (I can see this when show the cart). The problem is when I use getTotalQuantity() function, may be that when I send a add to cart , this is consider as new item for getTotalQuantity() function, why the result with getTotalQuantity() function is diferent to sizeof (Cart::getContent()).

I hope I was clear, please excuse for me english.

**Comment by frezno** [comment]
@j574144 not quite sure what exactly you mean.
`getTotalQuantity()` counts the total **quantity** of the products added to the cart, whereas `getContent()` shows the number of the **individual products** added to the cart.

**Comment by j574144** [comment]
Hi. @frezno.

Thanks for your reply. This is a understanding issue from my side. Please consider this as an solved theme.
