### ISSUE TITLE
Laravel 5.5 incompatibility

### ISSUE THREAD

**Issue by higherstudio** [darryldecode/laravelshoppingcart#96]
composer require darryldecode/cart

Returns: 
- darryldecode/cart 3.0.0 requires illuminate/translation 5.0.*|5.1.*|5.2.*|5.3.*|5.4.* -> satisfiable by illuminate/translation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

**Comment by publiux** [comment]
In case you are interested, I created a fork of this project and updated it to work with Laravel 5.5 and package autodiscovery. The forked repo is at https://github.com/publiux/laravelshoppingcart

**Comment by darryldecode** [comment]
Should be fixed in this PR: https://github.com/darryldecode/laravelshoppingcart/pull/97
