### ISSUE TITLE
Auto increment cart id

### ISSUE THREAD

**Issue by salmanmomin** [darryldecode/laravelshoppingcart#99]
Is there any way where the cart increments automatically?
For example,
If I add an item to cart like this without supplying id parameter so that it will automatically increment the id.
Cart::add('Sample Item', 100.99, 2, array());

**Comment by Acen** [comment]
Wouldn't you want to initialize the cart (with an ID) when the session starts (or to connect to an existing one). It's kind of forcing the library to then take over session handling, which is probably out of scope.

**Comment by frezno** [comment]
@salmanmomin - i'm not quite sure what you want to achieve with this.
The id refers to the item id of the item in your database table and it's not an incremented id of the items added to the cart.
Maybe you want to elaborate further your intentions.

**Comment by salmanmomin** [comment]
@frezno Previously I was confused with the id but now I have understood that the id is the product id and my issue has been solved now.

**Comment by drosendo** [comment]
Sorry to insist on this, but I have a case where autoincrement is necessary.

On my case, I can have a product that is a composition of other products.
In my case:

User selects a Product A + custom name (David) (product A is id "69").
The same user can acquire the product A but with different custom name (John), how would I store this? 
using the current method this would be stored over the previous add to cart on id 69.

Cheers,
david
